export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
// Person
export const GET_PERSONS = 'GET_PERSONS';
export const GET_PERSON = 'GET_PERSON';
export const ADD_PERSON = 'ADD_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const PERSON_ERROR = 'PERSON_ERROR';
// Research
export const GET_RESEARCHPOSTS = 'GET_RESEARCHPOSTS';
export const GET_RESEARCHPOST = 'GET_RESEARCHPOST';
export const ADD_RESEARCHPOST = 'ADD_RESEARCHPOST';
export const DELETE_RESEARCHPOST = 'DELETE_RESEARCHPOST';
export const RESEARCHPOST_ERROR = 'RESEARCHPOST_ERROR';
